PKGROOT		= /opt/mpiblast
NAME		= mpiblast_$(ROLLCOMPILER)_$(ROLLMPI)_$(ROLLNETWORK)
VERSION		= 1.6.0
RELEASE		= 1
TARBALL_POSTFIX	= tgz

SRC_SUBDIR	= mpiblast
MPIBLAST_NAME  =  mpiblast
MPIBLAST_FILE_NAME  =  mpiBLAST
MPIBLAST_VERSION  = 1.6.0

TGZ_PKGS = $(MPIBLAST_FILE_NAME)-$(MPIBLAST_VERSION).$(TARBALL_POSTFIX)
