#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
module-whatis "mpiblast"
module-whatis "Version: VERSION"
module-whatis "Description: mpiblast"
prepend-path PATH /opt/mpiblast/bin
END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion VERSION
END

(cd ROOT_PKGROOTMODULEROOT; /bin/ln -s .version.VERSION .version )
